# This rule is not used by the project kbrain itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the agents.kbrain.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kbrain
    app.kubernetes.io/managed-by: kustomize
  name: agentpool-editor-role
rules:
- apiGroups:
  - agents.kbrain.io
  resources:
  - agentpools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agents.kbrain.io
  resources:
  - agentpools/status
  verbs:
  - get
